### ISSUE TITLE
SumWithDefault doesn't work on Django 1.8

### ISSUE THREAD

**Issue by kevinmickey** [miratcan/qhonuskan-votes#24]
I was able to get the demo to run on Django 1.7 with little tweaks, but I'm having trouble with 1.8.  I can run the server, but I get this error when I try to go to the home page:

```
OperationalError at /
no such function: None
Error during template rendering
In template /Users/kevin/Downloads/qhonuskan-votes/demo/templates/home.html, error at line 43
{% for object in objects %}
```

When I open a shell, I can get ThreadModel.objects.all(), but when I try to run ThreadModel.objects_with_scores.all(),  I get:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/kevin/.envs/qhonuskan-votes/lib/python2.7/site-packages/django/db/models/query.py", line 138, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/Users/kevin/.envs/qhonuskan-votes/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/Users/kevin/.envs/qhonuskan-votes/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/kevin/.envs/qhonuskan-votes/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/Users/kevin/.envs/qhonuskan-votes/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/Users/kevin/.envs/qhonuskan-votes/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/kevin/.envs/qhonuskan-votes/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/kevin/.envs/qhonuskan-votes/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/kevin/.envs/qhonuskan-votes/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/kevin/.envs/qhonuskan-votes/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such function: None
```

**Comment by kevinmickey** [comment]
It appears the issue was with SumWithDefault in [qhonuskan_votes/utils.py](../blob/master/qhonuskan_votes/utils.py).  Not sure what the problem exactly is, but see: 
http://stackoverflow.com/questions/553038/treat-null-as-0-in-django-model
http://stackoverflow.com/questions/21522282/django-aggregate-by-queryset
https://code.djangoproject.com/ticket/10929

This is ugly, but it works across django versions:
```python
# qhonuskan-votes/models.py
import django

...

class ObjectsWithScoresManager(models.Manager):
    """
    Returns objects with their scores
    """
    def get_queryset(self):
        if django.VERSION < (1, 8):
            from qhonuskan_votes.utils import SumWithDefault
            return super(ObjectsWithScoresManager, self).get_queryset().annotate(
               vote_score=SumWithDefault(
                   '%svote__value' % self.model._meta.model_name, default=0
               )
            )
        else:
            from django.db.models import Sum
            from django.db.models.functions import Coalesce
            return super(ObjectsWithScoresManager, self).get_queryset().annotate(
                vote_score=Coalesce(Sum('%svote__value' % self.model._meta.model_name), 0)
            )
```

**Comment by kevinmickey** [comment]
Available here: https://github.com/kevinmickey/qhonuskan-votes/tree/filestructure

**Comment by miratcan** [comment]
This Project accepts [Octotreats](https://octotreat.com). You may promise the owner a treat upon completion of this Issue [here](https://octotreat.com/projects/12/treats/new?issue_id=35)
